apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: single-container-app
  namespace: single-container-app
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: single-container-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: single-container-app
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: single-container-app-
      labels:
        build.appstudio.openshift.io/application: single-container-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: single-container-app
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: single-container-app
    spec:
      params:
      - name: git-url
        value: https://github.com/jduimovich/single-container-app
      - name: output-image
        value: quay.io/jduimovich0/single-container-app:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:5cc4c4afd4c28d8918975b29312e03d623492538
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: single-container-app/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
